title: Ruby Quick Reference
description: Quick reference for efficient coding 
#theme: jekyll-theme-minimal
theme: minima
exclude:
  - README.md
  - app.rb
  - app_each.sh
  - _codes/
  - makefile
  - Gemfile
  - Gemfile.lock
