title: Ruby Quick Reference
description: A concise guide summarizing the fundamental features of Ruby in an accessible format
theme: jekyll-theme-minimal
exclude:
 - README.md
 - app.sh
 - app_readme.sh
 - codes
 - makefile
