title: Ruby Quick Reference
description: Quick reference for efficient coding 
theme: minima
exclude:
  - README.md
  - app.rb
  - app_each.sh
  - _codes/
  - YS1/
  - makefile
  - Gemfile
  - Gemfile.lock
